config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static





urlpatterns = [
    path("", include("core.urls", namespace = "home")),
    path("resources/", include("content.urls", namespace = "courses")),
    path("books/", include("books.urls", namespace="books")),
    path('admin/', admin.site.urls),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path
from .views import CoursesView as course_view
from .views import CoursePageView as course_page_view
from .views import CourseCategoryPageView as course_category_view
from .views import CourseSubCategoryPageView as course_subc_view

app_name = "courses"

urlpatterns = [
    path("", course_view, name="courses_view"),
    path("<int:pk>/<slug:resources_name>/", course_page_view, name="resources"),
    path("categories/<int:pk>/<slug:category_name>", course_category_view, name="category_view"),
    path("categories/<slug:category_name>/<int:pk>/<slug:subcategory_name>", course_subc_view,
         name="subcategory_view"),

]

core/urls.py
from django.urls import path
from .views import home as home_view

app_name = "core"

urlpatterns = [path("", home_view ,name="core")]

templates/course/category_view.html
{% extends 'base.html' %}

{% block content %}
   {% for subcategory in subcategories_objs %}
      {% for course in subcategory.courses.all %}
      <a href = "{% url 'courses:resources' course.id course.slug  %}">
        <p>{{course.title}}</p>
      </a>
      {% endfor %}
   {% endfor %}

{% endblock content %}

templates/course/course_view.html
{% extends 'base.html' %}

{% block content %}
   <p>{{course.title}}</p>
{% endblock content %}

templates/course/courses_list.html
{% extends 'base.html' %}

{% block content %}

 <div class = "category">
     <ul>
          {% for category in category_obj %}
            <li>
              <a href="{% url 'courses:category_view' category.id category.slug %}" >{{ category.name }}</a>
            </li>

              <ul>       
                 {% for sub_category in category.SubCategoryList.all %}
                       <li>
                        <a href="{% url 'courses:subcategory_view' category.slug sub_category.id sub_category.slug  %}"> {{ sub_category.name }}</a> 
                       </li> 
                 {% endfor %}    
              </ul>
            
           {% endfor %}
       
     </ul>
    
 </div 

 <div class="content">
    {% for course in page_obj.object_list  %}
    <a href = "{% url 'courses:resources' course.id course.slug %}">
      <p>{{ course.title }}</p>
    </a> 
   {% endfor %}
 </div>

  

 <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

templates/course/subcategory_view.html
{% extends 'base.html' %}

{% block content %}

  <div class = "sub_category_courses">
    {% for course in courses %}
      <a href = "{% url 'courses:resources' course.id course.slug  %}">
        <p>{{course.title}}</p>
      </a>
    {% endfor %}
  </div>

{% endblock content %}