books/urls.py
from django.urls.conf import path
from .views import home_view,file_view

app_name = "books"

urlpatterns = [
    path("",home_view,name="home_view"),
    path("files/<int:pk>/<str:subject_name>/",file_view,name="files_view")

]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static





urlpatterns = [
    path("", include("core.urls", namespace = "home")),
    path("resources/", include("content.urls", namespace = "courses")),
    path("books/", include("books.urls", namespace="books")),
    path('admin/', admin.site.urls),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import home as home_view

app_name = "core"

urlpatterns = [path("", home_view ,name="core")]

books/models.py
from django.db import models
from core import models as core_models
from froala_editor.fields import FroalaField


# Create your models here.

class Field(core_models.TimeStampedModel):
    """ Field Model """

    field_name = models.CharField(max_length=50)


class Subject(core_models.TimeStampedModel):
    """ Subject Model """

    field = models.ForeignKey("Field", on_delete=models.CASCADE)

    sem_choices = (
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "4"),
        ("5", "5"),
        ("6", "6"),
        ("7", "7"),
        ("8", "8"),
    )

    sem = models.CharField(max_length=10, choices=sem_choices)

    year_choices = (
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "4"),
    )

    year = models.CharField(max_length=10, choices=year_choices)

    name = models.CharField(max_length=100)


class File(core_models.TimeStampedModel):
    """ File  Model """

    title = models.CharField(max_length=251)
    description = FroalaField()
    subject = models.ForeignKey("Subject",related_name="files", on_delete=models.CASCADE)
    file = models.FileField(upload_to="books_files", null=True, blank=True)
    is_public = models.BooleanField(default=False)

books/views.py
from django.core.exceptions import FieldDoesNotExist, ObjectDoesNotExist
from django.http.response import Http404, HttpResponse
from django.shortcuts import render
from . import models

# Create your views here.

def home_view(request):

    fields = models.Field.objects.all()
    field, sem, year = request.GET.get("field",None), request.GET.get("sem",None),request.GET.get("year",None)
    subjects = None

    try:
        get_field = models.Field.objects.get(field_name=field)
        subjects = models.Subject.objects.filter(field=get_field,sem=sem,year=year)
    except ObjectDoesNotExist:
        subjects = None
        
        



    context = {
       "fields":fields,
       "range_sem":range(1,9),
       "range_year":range(1,5),
       "subjects":subjects,
    }
    return render(request,"books/home_view.html",context)


def file_view(request,pk,subject_name):
    get_subject = models.Subject.objects.get(pk=pk,name=subject_name)

    files = get_subject.files.all

    context = {
        "files":files
    } 

    return render(request,"books/files_view.html",context)

templates/books/files_view.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

  <div class="row align-items-center">
    

    <div class="col">
      One of three columns
    </div>

    <div class="col">
      <h2>books</h2>

      {% for file in files %}
          <div class="card">
             <div class="card-body">
                {{file.title}}
             </div>
          </div>  
      {% endfor %}
      
    </div> 

  </div>
</div>
{% endblock content %}

templates/books/home_view.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
       <p>gtu books</p>
    <form action="{% url 'books:home_view' %}" method="GET">
       <div class="row align-items-center">
        <div class="col">
            <div class = "select__field">
                <label for="field-select">Choose a field:</label>
                <select name="field" id="field-select" class="form-select form-select-sm" aria-label=".form-select-sm example">
                  <option value="">--Please select an field--</option>
                  {% for field in fields %}
                  <option value="{{field.field_name}}">{{field.field_name}}</option>
                  {% endfor %} 
                </select>
              </div>
        </div>
        <div class="col">
            <div class = "select__sem">
                <label for="field-sem">Choose a sem:</label>
                <select name="sem" id="field-sem" class="form-select form-select-sm" aria-label=".form-select-sm example">
                    <option value="">--Please select an sem--</option>
                    {% for sem in range_sem %}
                    <option value="{{sem}}">{{sem}}</option>
                    {% endfor %}   
                </select>
              </div>
        </div>
        <div class="col">
            <div class = "select__year">
                <label for="field-year">Choose a year:</label>
                <select name = "year" id="field-year" class="form-select form-select-sm" aria-label=".form-select-sm example>
                  <option value="">--Please select an year--</option>
                  {% for year in range_year %}
                  <option value="{{year}}">{{year}}</option>
                  {% endfor %} 
                </select>
              </div>
        </div>
        <div class="col">
            <div class = "submit">
             <input class="btn btn-primary" type="submit" value="submit" />
        </div>
       </div>
      </div>
    </form>  
    
      {% for subject in subjects %}
         <div class="card">
            <div class="card-body">
                <a href="{% url 'books:files_view' subject.id subject.name %}" ><p>{{subject.name}}</p></a>
            </div>
        </div>
 
      {% endfor %}
      
   
  </div>

{% endblock content %}